// ✅ Fix for TypeScript global declaration conflicts
import type { SupabaseClient } from "@supabase/supabase-js";

// Extend the Window interface safely without redeclaring incompatible types
declare global {
  interface Window {
    $plasmic?: {
      updateGlobalState?: (key: string, value: any) => void;
    };
    supabase?: SupabaseClient;
    __supabaseReady__?: boolean;
  }
}

// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { useEffect } from "react";
import { supabase } from "../../lib/supabaseClient"; // ✅ same client your app uses
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import { PlasmicAppCampaigns } from "../../components/plasmic/ad_buy/PlasmicAppCampaigns";
import { useRouter } from "next/router";

function AppCampaigns() {
  const router = useRouter();

  useEffect(() => {
    (async () => {
      try {
        console.log("[Campaigns] 🔄 Waiting for Supabase...");

        // Wait for Supabase to initialize globally
        let retries = 20;
        while ((!window.__supabaseReady__ || !window.supabase) && retries > 0) {
          await new Promise((r) => setTimeout(r, 150));
          retries--;
        }

        if (!window.supabase) {
          console.error("[Campaigns] ❌ Supabase never initialized");
          return;
        }

        console.log("[Campaigns] ✅ Supabase ready, fetching campaigns...");

        const { data, error } = await window.supabase
          .from("campaigns")
          .select("*");

        if (error) throw error;

        console.log("[Campaigns] 📦 Supabase campaigns:", data);

        // ✅ Make available to Plasmic states
        window.$plasmic?.updateGlobalState?.("campaigns", data);
      } catch (err) {
        console.error("[Campaigns] ❌ Supabase query failed:", err);
      }
    })();
  }, []);

  return (
    <PageParamsProvider__
      route={router?.pathname}
      params={router?.query}
      query={router?.query}
    >
      <PlasmicAppCampaigns />
    </PageParamsProvider__>
  );
}

export default AppCampaigns;
