/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fKsvVS5XnenaZB1533Xwx5
// Component: SapC-YuZNb7v

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import AppLayout from "../../AppLayout"; // plasmic-import: 3-ESBXWrTc3V/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: fKsvVS5XnenaZB1533Xwx5/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: fKsvVS5XnenaZB1533Xwx5/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fKsvVS5XnenaZB1533Xwx5/projectcss
import sty from "./PlasmicAppEvents.module.css"; // plasmic-import: SapC-YuZNb7v/css

import ToggleLeftSvgIcon from "./icons/PlasmicIcon__ToggleLeftSvg"; // plasmic-import: 4yAUxwLLbNVI/icon
import DollarSign1SvgIcon from "./icons/PlasmicIcon__DollarSign1Svg"; // plasmic-import: e7anIF66FNNl/icon
import MapPinSvgIcon from "./icons/PlasmicIcon__MapPinSvg"; // plasmic-import: -SnCIoFrsIAj/icon
import MoveUpRightSvgIcon from "./icons/PlasmicIcon__MoveUpRightSvg"; // plasmic-import: yPw2r6PF5Lx4/icon
import ClockSvgIcon from "./icons/PlasmicIcon__ClockSvg"; // plasmic-import: zWug_iP9VWff/icon
import EditActiveSvgIcon from "./icons/PlasmicIcon__EditActiveSvg"; // plasmic-import: 2DRB0xm4Rnlz/icon
import EnterSvgIcon from "./icons/PlasmicIcon__EnterSvg"; // plasmic-import: x8a8y30xjfZo/icon

createPlasmicElementProxy;

export type PlasmicAppEvents__VariantMembers = {};
export type PlasmicAppEvents__VariantsArgs = {};
type VariantPropType = keyof PlasmicAppEvents__VariantsArgs;
export const PlasmicAppEvents__VariantProps = new Array<VariantPropType>();

export type PlasmicAppEvents__ArgsType = {};
type ArgPropType = keyof PlasmicAppEvents__ArgsType;
export const PlasmicAppEvents__ArgProps = new Array<ArgPropType>();

export type PlasmicAppEvents__OverridesType = {
  root?: Flex__<"div">;
  appLayout?: Flex__<typeof AppLayout>;
  mainParentempty3?: Flex__<"div">;
  tableScrollWrapper4?: Flex__<"div">;
  innerTable4?: Flex__<"div">;
  campaignHeader4?: Flex__<"div">;
  leadsHeader4?: Flex__<"div">;
  callsHeader4?: Flex__<"div">;
  spendHeader4?: Flex__<"div">;
  emptyParent4?: Flex__<"div">;
  halfOpacitygradient4?: Flex__<"div">;
  campaignRow6?: Flex__<"div">;
  offOn6?: Flex__<"div">;
  budget6?: Flex__<"div">;
  mobileedit32?: Flex__<"svg">;
  location6?: Flex__<"div">;
  missed?: Flex__<"div">;
  voicemail?: Flex__<"div">;
  received?: Flex__<"div">;
  campaign6?: Flex__<"div">;
  leads6?: Flex__<"div">;
  mobileedit33?: Flex__<"svg">;
  calls6?: Flex__<"div">;
  mobileedit34?: Flex__<"svg">;
  spend6?: Flex__<"div">;
  mobileedit35?: Flex__<"svg">;
  imageFade4?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  tableScroll?: Flex__<typeof Embed>;
  fadeStyles?: Flex__<typeof Embed>;
};

export interface DefaultAppEventsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAppEvents__RenderFunc(props: {
  variants: PlasmicAppEvents__VariantsArgs;
  args: PlasmicAppEvents__ArgsType;
  overrides: PlasmicAppEvents__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "appLayout.popOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "calls",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => []
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicAppEvents.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAppEvents.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicAppEvents.pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={PlasmicAppEvents.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicAppEvents.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <AppLayout
            data-plasmic-name={"appLayout"}
            data-plasmic-override={overrides.appLayout}
            className={classNames("__wab_instance", sty.appLayout)}
            contents2={
              <div
                data-plasmic-name={"mainParentempty3"}
                data-plasmic-override={overrides.mainParentempty3}
                className={classNames(projectcss.all, sty.mainParentempty3)}
              >
                <div
                  data-plasmic-name={"tableScrollWrapper4"}
                  data-plasmic-override={overrides.tableScrollWrapper4}
                  className={classNames(
                    projectcss.all,
                    sty.tableScrollWrapper4,
                    "table-scroll"
                  )}
                >
                  <div
                    data-plasmic-name={"innerTable4"}
                    data-plasmic-override={overrides.innerTable4}
                    className={classNames(projectcss.all, sty.innerTable4)}
                  >
                    <div
                      data-plasmic-name={"campaignHeader4"}
                      data-plasmic-override={overrides.campaignHeader4}
                      className={classNames(
                        projectcss.all,
                        sty.campaignHeader4,
                        (() => {
                          try {
                            return !($state?.calls && $state.calls.length > 0)
                              ? "halfOpacity"
                              : "";
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___804P
                        )}
                      >
                        <ToggleLeftSvgIcon
                          className={classNames(projectcss.all, sty.svg__tjz3Q)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__e9Ey,
                            "geologica-text-medium"
                          )}
                        >
                          {"Name"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__g6MvO
                        )}
                      >
                        <DollarSign1SvgIcon
                          className={classNames(projectcss.all, sty.svg__s03X3)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dCRgz,
                            "geologica-text-medium"
                          )}
                        >
                          {"Type"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__doAC
                        )}
                      >
                        <MapPinSvgIcon
                          className={classNames(projectcss.all, sty.svg__mTqOq)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kgb31,
                            "geologica-text-medium"
                          )}
                        >
                          {"Status"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zf6Na
                        )}
                      >
                        <MoveUpRightSvgIcon
                          className={classNames(projectcss.all, sty.svg__mE0Af)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pkRo2,
                            "geologica-text-medium"
                          )}
                        >
                          {"Duration"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"leadsHeader4"}
                        data-plasmic-override={overrides.leadsHeader4}
                        className={classNames(projectcss.all, sty.leadsHeader4)}
                      >
                        <DollarSign1SvgIcon
                          className={classNames(projectcss.all, sty.svg__zr6SD)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___5RUh,
                            "geologica-text-medium"
                          )}
                        >
                          {"Phone"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"callsHeader4"}
                        data-plasmic-override={overrides.callsHeader4}
                        className={classNames(projectcss.all, sty.callsHeader4)}
                      >
                        <DollarSign1SvgIcon
                          className={classNames(projectcss.all, sty.svg__pbA2R)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9Bgt6,
                            "geologica-text-medium"
                          )}
                        >
                          {"Email"}
                        </div>
                      </div>
                      {false ? (
                        <div
                          data-plasmic-name={"spendHeader4"}
                          data-plasmic-override={overrides.spendHeader4}
                          className={classNames(
                            projectcss.all,
                            sty.spendHeader4
                          )}
                        >
                          <DollarSign1SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__neC5A
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mozi,
                              "geologica-text-medium"
                            )}
                          >
                            {"Spend"}
                          </div>
                        </div>
                      ) : null}
                    </div>
                    <div
                      data-plasmic-name={"emptyParent4"}
                      data-plasmic-override={overrides.emptyParent4}
                      className={classNames(projectcss.all, sty.emptyParent4)}
                    >
                      <div
                        data-plasmic-name={"halfOpacitygradient4"}
                        data-plasmic-override={overrides.halfOpacitygradient4}
                        className={classNames(
                          projectcss.all,
                          sty.halfOpacitygradient4,
                          "halfOpacitygradient"
                        )}
                      >
                        {(_par =>
                          !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                          (() => {
                            try {
                              return [
                                {
                                  id: "call-001",
                                  full_name: "Debra Santos",
                                  from_number: "+15553334444",
                                  lead_type: "Cryotherapy",
                                  status: "missed",
                                  duration_seconds: 0,
                                  created_at: "2025-12-05T17:12:00Z"
                                },
                                {
                                  id: "call-002",
                                  full_name: "James Coleman",
                                  from_number: "+15556667777",
                                  lead_type: "Window Replacement",
                                  status: "received",
                                  duration_seconds: 112,
                                  created_at: "2025-12-05T14:45:00Z"
                                },
                                {
                                  id: "call-003",
                                  full_name: null,
                                  from_number: "+15554443333",
                                  lead_type: "Cryotherapy",
                                  status: "voicemail",
                                  duration_seconds: 4,
                                  created_at: "2025-12-04T20:10:00Z"
                                }
                              ];
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return [];
                              }
                              throw e;
                            }
                          })()
                        ).map((__plasmic_item_0, __plasmic_idx_0) => {
                          const currentItem = __plasmic_item_0;
                          const currentIndex = __plasmic_idx_0;
                          return (
                            <div
                              data-plasmic-name={"campaignRow6"}
                              data-plasmic-override={overrides.campaignRow6}
                              className={classNames(
                                projectcss.all,
                                sty.campaignRow6,
                                ``
                              )}
                              key={currentIndex}
                            >
                              <div
                                data-plasmic-name={"offOn6"}
                                data-plasmic-override={overrides.offOn6}
                                className={classNames(
                                  projectcss.all,
                                  sty.offOn6
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__gBs8G
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return (() => {
                                          // Prefer full_name if available
                                          if (currentItem.full_name)
                                            return currentItem.full_name;

                                          const raw =
                                            currentItem.from_number || "";

                                          // Match +1XXXXXXXXXX or 10 digits
                                          const match = raw.match(
                                            /^\+?1?(\d{3})(\d{3})(\d{4})$/
                                          );
                                          if (!match) return raw; // fallback if formatting isn't possible

                                          const [, area, mid, last] = match;
                                          return `+1 (${area}) ${mid}-${last}`;
                                        })();
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Debra Santos";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__jmIut
                                  )}
                                >
                                  {"Today at "}
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__fQhFx
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__vb07C
                                    )}
                                  />

                                  <ClockSvgIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg___1ZtUm
                                    )}
                                    role={"img"}
                                  />

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__uJyv9,
                                      "geologica-text-regular"
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return (() => {
                                            const ts = new Date(
                                              currentItem.created_at
                                            );
                                            const now = new Date();
                                            const diffMs = now - ts;
                                            const diffMinutes = Math.floor(
                                              diffMs / 60000
                                            );

                                            if (diffMinutes < 1)
                                              return "Just now";
                                            if (diffMinutes < 60)
                                              return `${diffMinutes} minute${diffMinutes === 1 ? "" : "s"} ago`;

                                            const diffHours = Math.floor(
                                              diffMinutes / 60
                                            );
                                            if (diffHours < 24)
                                              return `${diffHours} hour${diffHours === 1 ? "" : "s"} ago`;

                                            const diffDays = Math.floor(
                                              diffHours / 24
                                            );
                                            return `${diffDays} day${diffDays === 1 ? "" : "s"} ago`;
                                          })();
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "8 minutes ago";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___6NnnM,
                                      "geologica-text-regular"
                                    )}
                                  >
                                    {"\u00b7"}
                                  </div>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__aq5Il,
                                      "geologica-text-regular"
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return (() => {
                                            const ts = new Date(
                                              currentItem.created_at
                                            );
                                            const month = String(
                                              ts.getMonth() + 1
                                            ).padStart(2, "0");
                                            const day = String(
                                              ts.getDate()
                                            ).padStart(2, "0");
                                            const year = ts.getFullYear();
                                            return `${month}/${day}/${year}`;
                                          })();
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "12/04/2025";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"budget6"}
                                data-plasmic-override={overrides.budget6}
                                className={classNames(
                                  projectcss.all,
                                  sty.budget6
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__otOle
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__t6ZA
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return currentItem.lead_type;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "Cryotherapy";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                </div>
                                <EditActiveSvgIcon
                                  data-plasmic-name={"mobileedit32"}
                                  data-plasmic-override={overrides.mobileedit32}
                                  className={classNames(
                                    projectcss.all,
                                    sty.mobileedit32
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"location6"}
                                data-plasmic-override={overrides.location6}
                                className={classNames(
                                  projectcss.all,
                                  sty.location6
                                )}
                              >
                                {(() => {
                                  try {
                                    return currentItem.status == "missed";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <div
                                    data-plasmic-name={"missed"}
                                    data-plasmic-override={overrides.missed}
                                    className={classNames(
                                      projectcss.all,
                                      sty.missed
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__jVhSm
                                      )}
                                    >
                                      <React.Fragment>
                                        {(() => {
                                          try {
                                            return currentItem.status;
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return "Cryotherapy";
                                            }
                                            throw e;
                                          }
                                        })()}
                                      </React.Fragment>
                                    </div>
                                  </div>
                                ) : null}
                                {(() => {
                                  try {
                                    return currentItem.status == "voicemail";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <div
                                    data-plasmic-name={"voicemail"}
                                    data-plasmic-override={overrides.voicemail}
                                    className={classNames(
                                      projectcss.all,
                                      sty.voicemail
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__d607C
                                      )}
                                    >
                                      <React.Fragment>
                                        {(() => {
                                          try {
                                            return currentItem.status;
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return "Cryotherapy";
                                            }
                                            throw e;
                                          }
                                        })()}
                                      </React.Fragment>
                                    </div>
                                  </div>
                                ) : null}
                                {(() => {
                                  try {
                                    return currentItem.status == "received";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return true;
                                    }
                                    throw e;
                                  }
                                })() ? (
                                  <div
                                    data-plasmic-name={"received"}
                                    data-plasmic-override={overrides.received}
                                    className={classNames(
                                      projectcss.all,
                                      sty.received
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__lh4Lr
                                      )}
                                    >
                                      <React.Fragment>
                                        {(() => {
                                          try {
                                            return currentItem.status;
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return "Cryotherapy";
                                            }
                                            throw e;
                                          }
                                        })()}
                                      </React.Fragment>
                                    </div>
                                  </div>
                                ) : null}
                              </div>
                              <div
                                data-plasmic-name={"campaign6"}
                                data-plasmic-override={overrides.campaign6}
                                className={classNames(
                                  projectcss.all,
                                  sty.campaign6
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__zD9Bh
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__vLOeB
                                    )}
                                  />

                                  <ClockSvgIcon
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg___9ABhS
                                    )}
                                    role={"img"}
                                  />

                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___95JzO,
                                      "geologica-text-regular"
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return (() => {
                                            return (() => {
                                              const sec = Number(
                                                currentItem.duration_seconds
                                              );
                                              if (
                                                sec == null ||
                                                Number.isNaN(sec)
                                              )
                                                return "";
                                              if (sec < 60) return `${sec}s`;
                                              const minutes = Math.floor(
                                                sec / 60
                                              );
                                              const seconds = sec % 60;
                                              if (minutes < 60) {
                                                return seconds > 0
                                                  ? `${minutes}m ${seconds}s`
                                                  : `${minutes}m`;
                                              }
                                              const hours = Math.floor(
                                                minutes / 60
                                              );
                                              const remMin = minutes % 60;
                                              if (remMin > 0) {
                                                return `${hours}h ${remMin}m`;
                                              }
                                              return `${hours}h`;
                                            })();
                                          })();
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "SMS";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                </div>
                              </div>
                              <div
                                data-plasmic-name={"leads6"}
                                data-plasmic-override={overrides.leads6}
                                className={classNames(
                                  projectcss.all,
                                  sty.leads6
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__nDe
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__obcPj
                                    )}
                                  >
                                    {"-"}
                                  </div>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__jaoIc
                                    )}
                                  >
                                    {"$- each"}
                                  </div>
                                </div>
                                <EditActiveSvgIcon
                                  data-plasmic-name={"mobileedit33"}
                                  data-plasmic-override={overrides.mobileedit33}
                                  className={classNames(
                                    projectcss.all,
                                    sty.mobileedit33
                                  )}
                                  role={"img"}
                                />
                              </div>
                              <div
                                data-plasmic-name={"calls6"}
                                data-plasmic-override={overrides.calls6}
                                className={classNames(
                                  projectcss.all,
                                  sty.calls6
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__apTyR
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___4NUk7
                                    )}
                                  >
                                    {"-"}
                                  </div>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__keExB
                                    )}
                                  >
                                    {"$24.53 each"}
                                  </div>
                                </div>
                                <EditActiveSvgIcon
                                  data-plasmic-name={"mobileedit34"}
                                  data-plasmic-override={overrides.mobileedit34}
                                  className={classNames(
                                    projectcss.all,
                                    sty.mobileedit34
                                  )}
                                  role={"img"}
                                />
                              </div>
                              {false ? (
                                <div
                                  data-plasmic-name={"spend6"}
                                  data-plasmic-override={overrides.spend6}
                                  className={classNames(
                                    projectcss.all,
                                    sty.spend6
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__cDsUy
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__dJgLh
                                      )}
                                    >
                                      {"-"}
                                    </div>
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___3L45E
                                      )}
                                    >
                                      {"Since 10/15/2025"}
                                    </div>
                                  </div>
                                  <EditActiveSvgIcon
                                    data-plasmic-name={"mobileedit35"}
                                    data-plasmic-override={
                                      overrides.mobileedit35
                                    }
                                    className={classNames(
                                      projectcss.all,
                                      sty.mobileedit35
                                    )}
                                    role={"img"}
                                  />
                                </div>
                              ) : null}
                            </div>
                          );
                        })}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__shYl
                        )}
                      >
                        {false ? (
                          <div
                            data-plasmic-name={"imageFade4"}
                            data-plasmic-override={overrides.imageFade4}
                            className={classNames(
                              projectcss.all,
                              sty.imageFade4,
                              "imageFade"
                            )}
                          >
                            <PlasmicImg__
                              data-plasmic-name={"img"}
                              data-plasmic-override={overrides.img}
                              alt={""}
                              class={``}
                              className={classNames(sty.img)}
                              displayHeight={"165px"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"100%"}
                              loading={"eager"}
                              src={{
                                src: "/plasmic/ad_buy/images/samplePng.png",
                                fullWidth: 1971,
                                fullHeight: 1151,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                        ) : null}
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rzaMc,
                            "geologica-text-medium"
                          )}
                        >
                          {"Calls"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__loY5A,
                            "geologica-text-medium"
                          )}
                        >
                          {
                            "Automated outbound calls that follow up instantly and persistently. Starts once your campaign goes live."
                          }
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aE48I
                          )}
                          onClick={async event => {
                            const $steps = {};

                            $steps["goToAppCampaigns"] = true
                              ? (() => {
                                  const actionArgs = {
                                    destination: `/app/campaigns`
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["goToAppCampaigns"] != null &&
                              typeof $steps["goToAppCampaigns"] === "object" &&
                              typeof $steps["goToAppCampaigns"].then ===
                                "function"
                            ) {
                              $steps["goToAppCampaigns"] =
                                await $steps["goToAppCampaigns"];
                            }
                          }}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ejwFv,
                              "geologica-text-medium"
                            )}
                          >
                            {"Create Campaign"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__aazD
                            )}
                          >
                            {false ? (
                              <EnterSvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__tt03
                                )}
                                role={"img"}
                              />
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__nJkT,
                                "geologica-h1"
                              )}
                            >
                              {"C"}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            }
            onPopOpenChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["appLayout", "popOpen"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            page={"events"}
            popOpen={generateStateValueProp($state, ["appLayout", "popOpen"])}
          />

          <Embed
            data-plasmic-name={"tableScroll"}
            data-plasmic-override={overrides.tableScroll}
            className={classNames("__wab_instance", sty.tableScroll)}
            code={
              "<style>\n\n.table-scroll {\n  overflow-x: auto !important;\n  overflow-y: visible !important;\n  -webkit-overflow-scrolling: touch !important;\n  display: block !important;\n  position: relative !important;\n  white-space: nowrap !important;\n}\n\n</style>"
            }
          />

          <Embed
            data-plasmic-name={"fadeStyles"}
            data-plasmic-override={overrides.fadeStyles}
            className={classNames("__wab_instance", sty.fadeStyles)}
            code={
              "<style>\n/* Fade an image from top (100%) \u2192 bottom (0%) */\n.imageFade {\n  position: relative;\n  display: block;\n\n  /* Apply mask to this entire container (Plasmic wraps img) */\n  -webkit-mask-image: linear-gradient(\n    to bottom,\n    rgba(0,0,0,1.0) 0%,     /* fully visible at the top */\n    rgba(0,0,0,0.85) 40%,   /* slight softening */\n    rgba(0,0,0,0.40) 75%,   /* stronger fade */\n    rgba(0,0,0,0.0) 100%    /* invisible at very bottom */\n  );\n  mask-image: linear-gradient(\n    to bottom,\n    rgba(0,0,0,1.0) 0%,\n    rgba(0,0,0,0.85) 40%,\n    rgba(0,0,0,0.40) 75%,\n    rgba(0,0,0,0.0) 100%\n  );\n\n  -webkit-mask-size: 100% 100%;\n  mask-size: 100% 100%;\n  -webkit-mask-repeat: no-repeat;\n  mask-repeat: no-repeat;\n}\n</style>\n\n\n<style>\n.halfOpacitygradient {\n  position: relative;\n\n  -webkit-mask-image: linear-gradient(\n    to bottom,\n    rgba(0,0,0,0.50) 0%,     /* 50% visible at top */\n    rgba(0,0,0,0.35) 45%,   /* soften through row 1 */\n    rgba(0,0,0,0.15) 75%,   /* light fade through row 2 */\n    rgba(0,0,0,0.05) 100%   /* nearly invisible at very bottom */\n  );\n  mask-image: linear-gradient(\n    to bottom,\n    rgba(0,0,0,0.50) 0%,\n    rgba(0,0,0,0.35) 45%,\n    rgba(0,0,0,0.15) 75%,\n    rgba(0,0,0,0.05) 100%\n  );\n\n  -webkit-mask-size: 100% 100%;\n  mask-size: 100% 100%;\n  -webkit-mask-repeat: no-repeat;\n  mask-repeat: no-repeat;\n}\n</style>\n\n\n\n\n<style>\n/* ---------------------------------------------\n   SIMPLE 50% OPACITY (unchanged)\n--------------------------------------------- */\n.halfOpacity {\n  opacity: 0.5;\n}\n.halfOpacity * {\n  opacity: 1;\n}\n</style>"
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "appLayout",
    "mainParentempty3",
    "tableScrollWrapper4",
    "innerTable4",
    "campaignHeader4",
    "leadsHeader4",
    "callsHeader4",
    "spendHeader4",
    "emptyParent4",
    "halfOpacitygradient4",
    "campaignRow6",
    "offOn6",
    "budget6",
    "mobileedit32",
    "location6",
    "missed",
    "voicemail",
    "received",
    "campaign6",
    "leads6",
    "mobileedit33",
    "calls6",
    "mobileedit34",
    "spend6",
    "mobileedit35",
    "imageFade4",
    "img",
    "tableScroll",
    "fadeStyles"
  ],
  appLayout: [
    "appLayout",
    "mainParentempty3",
    "tableScrollWrapper4",
    "innerTable4",
    "campaignHeader4",
    "leadsHeader4",
    "callsHeader4",
    "spendHeader4",
    "emptyParent4",
    "halfOpacitygradient4",
    "campaignRow6",
    "offOn6",
    "budget6",
    "mobileedit32",
    "location6",
    "missed",
    "voicemail",
    "received",
    "campaign6",
    "leads6",
    "mobileedit33",
    "calls6",
    "mobileedit34",
    "spend6",
    "mobileedit35",
    "imageFade4",
    "img"
  ],
  mainParentempty3: [
    "mainParentempty3",
    "tableScrollWrapper4",
    "innerTable4",
    "campaignHeader4",
    "leadsHeader4",
    "callsHeader4",
    "spendHeader4",
    "emptyParent4",
    "halfOpacitygradient4",
    "campaignRow6",
    "offOn6",
    "budget6",
    "mobileedit32",
    "location6",
    "missed",
    "voicemail",
    "received",
    "campaign6",
    "leads6",
    "mobileedit33",
    "calls6",
    "mobileedit34",
    "spend6",
    "mobileedit35",
    "imageFade4",
    "img"
  ],
  tableScrollWrapper4: [
    "tableScrollWrapper4",
    "innerTable4",
    "campaignHeader4",
    "leadsHeader4",
    "callsHeader4",
    "spendHeader4",
    "emptyParent4",
    "halfOpacitygradient4",
    "campaignRow6",
    "offOn6",
    "budget6",
    "mobileedit32",
    "location6",
    "missed",
    "voicemail",
    "received",
    "campaign6",
    "leads6",
    "mobileedit33",
    "calls6",
    "mobileedit34",
    "spend6",
    "mobileedit35",
    "imageFade4",
    "img"
  ],
  innerTable4: [
    "innerTable4",
    "campaignHeader4",
    "leadsHeader4",
    "callsHeader4",
    "spendHeader4",
    "emptyParent4",
    "halfOpacitygradient4",
    "campaignRow6",
    "offOn6",
    "budget6",
    "mobileedit32",
    "location6",
    "missed",
    "voicemail",
    "received",
    "campaign6",
    "leads6",
    "mobileedit33",
    "calls6",
    "mobileedit34",
    "spend6",
    "mobileedit35",
    "imageFade4",
    "img"
  ],
  campaignHeader4: [
    "campaignHeader4",
    "leadsHeader4",
    "callsHeader4",
    "spendHeader4"
  ],
  leadsHeader4: ["leadsHeader4"],
  callsHeader4: ["callsHeader4"],
  spendHeader4: ["spendHeader4"],
  emptyParent4: [
    "emptyParent4",
    "halfOpacitygradient4",
    "campaignRow6",
    "offOn6",
    "budget6",
    "mobileedit32",
    "location6",
    "missed",
    "voicemail",
    "received",
    "campaign6",
    "leads6",
    "mobileedit33",
    "calls6",
    "mobileedit34",
    "spend6",
    "mobileedit35",
    "imageFade4",
    "img"
  ],
  halfOpacitygradient4: [
    "halfOpacitygradient4",
    "campaignRow6",
    "offOn6",
    "budget6",
    "mobileedit32",
    "location6",
    "missed",
    "voicemail",
    "received",
    "campaign6",
    "leads6",
    "mobileedit33",
    "calls6",
    "mobileedit34",
    "spend6",
    "mobileedit35"
  ],
  campaignRow6: [
    "campaignRow6",
    "offOn6",
    "budget6",
    "mobileedit32",
    "location6",
    "missed",
    "voicemail",
    "received",
    "campaign6",
    "leads6",
    "mobileedit33",
    "calls6",
    "mobileedit34",
    "spend6",
    "mobileedit35"
  ],
  offOn6: ["offOn6"],
  budget6: ["budget6", "mobileedit32"],
  mobileedit32: ["mobileedit32"],
  location6: ["location6", "missed", "voicemail", "received"],
  missed: ["missed"],
  voicemail: ["voicemail"],
  received: ["received"],
  campaign6: ["campaign6"],
  leads6: ["leads6", "mobileedit33"],
  mobileedit33: ["mobileedit33"],
  calls6: ["calls6", "mobileedit34"],
  mobileedit34: ["mobileedit34"],
  spend6: ["spend6", "mobileedit35"],
  mobileedit35: ["mobileedit35"],
  imageFade4: ["imageFade4", "img"],
  img: ["img"],
  tableScroll: ["tableScroll"],
  fadeStyles: ["fadeStyles"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  appLayout: typeof AppLayout;
  mainParentempty3: "div";
  tableScrollWrapper4: "div";
  innerTable4: "div";
  campaignHeader4: "div";
  leadsHeader4: "div";
  callsHeader4: "div";
  spendHeader4: "div";
  emptyParent4: "div";
  halfOpacitygradient4: "div";
  campaignRow6: "div";
  offOn6: "div";
  budget6: "div";
  mobileedit32: "svg";
  location6: "div";
  missed: "div";
  voicemail: "div";
  received: "div";
  campaign6: "div";
  leads6: "div";
  mobileedit33: "svg";
  calls6: "div";
  mobileedit34: "svg";
  spend6: "div";
  mobileedit35: "svg";
  imageFade4: "div";
  img: typeof PlasmicImg__;
  tableScroll: typeof Embed;
  fadeStyles: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAppEvents__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAppEvents__VariantsArgs;
    args?: PlasmicAppEvents__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAppEvents__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAppEvents__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAppEvents__ArgProps,
          internalVariantPropNames: PlasmicAppEvents__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAppEvents__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAppEvents";
  } else {
    func.displayName = `PlasmicAppEvents.${nodeName}`;
  }
  return func;
}

export const PlasmicAppEvents = Object.assign(
  // Top-level PlasmicAppEvents renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    appLayout: makeNodeComponent("appLayout"),
    mainParentempty3: makeNodeComponent("mainParentempty3"),
    tableScrollWrapper4: makeNodeComponent("tableScrollWrapper4"),
    innerTable4: makeNodeComponent("innerTable4"),
    campaignHeader4: makeNodeComponent("campaignHeader4"),
    leadsHeader4: makeNodeComponent("leadsHeader4"),
    callsHeader4: makeNodeComponent("callsHeader4"),
    spendHeader4: makeNodeComponent("spendHeader4"),
    emptyParent4: makeNodeComponent("emptyParent4"),
    halfOpacitygradient4: makeNodeComponent("halfOpacitygradient4"),
    campaignRow6: makeNodeComponent("campaignRow6"),
    offOn6: makeNodeComponent("offOn6"),
    budget6: makeNodeComponent("budget6"),
    mobileedit32: makeNodeComponent("mobileedit32"),
    location6: makeNodeComponent("location6"),
    missed: makeNodeComponent("missed"),
    voicemail: makeNodeComponent("voicemail"),
    received: makeNodeComponent("received"),
    campaign6: makeNodeComponent("campaign6"),
    leads6: makeNodeComponent("leads6"),
    mobileedit33: makeNodeComponent("mobileedit33"),
    calls6: makeNodeComponent("calls6"),
    mobileedit34: makeNodeComponent("mobileedit34"),
    spend6: makeNodeComponent("spend6"),
    mobileedit35: makeNodeComponent("mobileedit35"),
    imageFade4: makeNodeComponent("imageFade4"),
    img: makeNodeComponent("img"),
    tableScroll: makeNodeComponent("tableScroll"),
    fadeStyles: makeNodeComponent("fadeStyles"),

    // Metadata about props expected for PlasmicAppEvents
    internalVariantProps: PlasmicAppEvents__VariantProps,
    internalArgProps: PlasmicAppEvents__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Events | AdBuy",
      description: "",
      ogImageSrc:
        "https://site-assets.plasmic.app/d1eac95f3934b1653900f60b4f2a55c6.png",
      canonical: ""
    }
  }
);

export default PlasmicAppEvents;
/* prettier-ignore-end */
