/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fKsvVS5XnenaZB1533Xwx5
// Component: -F6KTATRxFF2

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import AppLayout from "../../AppLayout"; // plasmic-import: 3-ESBXWrTc3V/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: fKsvVS5XnenaZB1533Xwx5/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: fKsvVS5XnenaZB1533Xwx5/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fKsvVS5XnenaZB1533Xwx5/projectcss
import sty from "./PlasmicAppCards.module.css"; // plasmic-import: -F6KTATRxFF2/css

createPlasmicElementProxy;

export type PlasmicAppCards__VariantMembers = {};
export type PlasmicAppCards__VariantsArgs = {};
type VariantPropType = keyof PlasmicAppCards__VariantsArgs;
export const PlasmicAppCards__VariantProps = new Array<VariantPropType>();

export type PlasmicAppCards__ArgsType = {};
type ArgPropType = keyof PlasmicAppCards__ArgsType;
export const PlasmicAppCards__ArgProps = new Array<ArgPropType>();

export type PlasmicAppCards__OverridesType = {
  root?: Flex__<"div">;
  appLayout?: Flex__<typeof AppLayout>;
  freeBox?: Flex__<"div">;
  text?: Flex__<"div">;
};

export interface DefaultAppCardsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAppCards__RenderFunc(props: {
  variants: PlasmicAppCards__VariantsArgs;
  args: PlasmicAppCards__ArgsType;
  overrides: PlasmicAppCards__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "appLayout.popOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicAppCards.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAppCards.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicAppCards.pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={PlasmicAppCards.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicAppCards.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <AppLayout
            data-plasmic-name={"appLayout"}
            data-plasmic-override={overrides.appLayout}
            btnClick={async event => {
              const $steps = {};

              $steps["runCode"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return async function addCard() {
                          console.log("▶️ addCard() clicked");

                          const res = await fetch("/api/stripe/add-card", {
                            method: "POST"
                          });

                          console.log("📡 Response status:", res.status);

                          let data;
                          try {
                            data = await res.json();
                            console.log("📦 Response JSON:", data);
                          } catch (e) {
                            console.error("❌ Failed to parse JSON:", e);
                            return;
                          }

                          if (data.error) {
                            console.error(
                              "❌ API returned an error:",
                              data.error
                            );
                            return;
                          }

                          if (data.url) {
                            console.log("➡️ Redirecting to:", data.url);
                            window.location.href = data.url;
                          } else {
                            console.warn("⚠️ No URL returned from API");
                          }
                        };
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode"] != null &&
                typeof $steps["runCode"] === "object" &&
                typeof $steps["runCode"].then === "function"
              ) {
                $steps["runCode"] = await $steps["runCode"];
              }
            }}
            className={classNames("__wab_instance", sty.appLayout)}
            contents2={
              <div
                data-plasmic-name={"freeBox"}
                data-plasmic-override={overrides.freeBox}
                className={classNames(projectcss.all, sty.freeBox)}
                onClick={async event => {
                  const $steps = {};

                  $steps["runCode"] = true
                    ? (() => {
                        const actionArgs = {
                          customFunction: async () => {
                            return (async () => {
                              async function addCard() {
                                console.log("\u25B6️ addCard() clicked");
                                const res = await fetch(
                                  "/api/stripe/add-card",
                                  { method: "POST" }
                                );
                                console.log(
                                  "\uD83D\uDCE1 Response status:",
                                  res.status
                                );
                                let data;
                                try {
                                  data = await res.json();
                                } catch (e) {
                                  console.error(
                                    "\u274C Failed to parse JSON:",
                                    e
                                  );
                                  return;
                                }
                                console.log(
                                  "\uD83D\uDCE6 Response JSON:",
                                  data
                                );
                                if (data.error) {
                                  console.error(
                                    "\u274C API returned:",
                                    data.error
                                  );
                                  return;
                                }
                                if (data.clientSecret) {
                                  const url = `https://billing.stripe.com/setup/${data.clientSecret}`;
                                  console.log("\u27A1️ Redirecting to:", url);
                                  window.location.href = url;
                                } else {
                                  console.warn(
                                    "\u26A0️ No clientSecret returned from API"
                                  );
                                }
                              }
                              return addCard();
                            })();
                          }
                        };
                        return (({ customFunction }) => {
                          return customFunction();
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["runCode"] != null &&
                    typeof $steps["runCode"] === "object" &&
                    typeof $steps["runCode"].then === "function"
                  ) {
                    $steps["runCode"] = await $steps["runCode"];
                  }
                }}
              >
                <div
                  data-plasmic-name={"text"}
                  data-plasmic-override={overrides.text}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text
                  )}
                >
                  {"Add Card"}
                </div>
              </div>
            }
            navBtnclick={async event => {
              const $steps = {};

              $steps["updateAppLayoutPopOpen"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["appLayout", "popOpen"]
                      },
                      operation: 0
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateAppLayoutPopOpen"] != null &&
                typeof $steps["updateAppLayoutPopOpen"] === "object" &&
                typeof $steps["updateAppLayoutPopOpen"].then === "function"
              ) {
                $steps["updateAppLayoutPopOpen"] =
                  await $steps["updateAppLayoutPopOpen"];
              }
            }}
            onPopOpenChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["appLayout", "popOpen"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            page={"cards"}
            popOpen={generateStateValueProp($state, ["appLayout", "popOpen"])}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "appLayout", "freeBox", "text"],
  appLayout: ["appLayout", "freeBox", "text"],
  freeBox: ["freeBox", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  appLayout: typeof AppLayout;
  freeBox: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAppCards__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAppCards__VariantsArgs;
    args?: PlasmicAppCards__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAppCards__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAppCards__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAppCards__ArgProps,
          internalVariantPropNames: PlasmicAppCards__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAppCards__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAppCards";
  } else {
    func.displayName = `PlasmicAppCards.${nodeName}`;
  }
  return func;
}

export const PlasmicAppCards = Object.assign(
  // Top-level PlasmicAppCards renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    appLayout: makeNodeComponent("appLayout"),
    freeBox: makeNodeComponent("freeBox"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicAppCards
    internalVariantProps: PlasmicAppCards__VariantProps,
    internalArgProps: PlasmicAppCards__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Cards | AdBuy",
      description: "",
      ogImageSrc:
        "https://site-assets.plasmic.app/d1eac95f3934b1653900f60b4f2a55c6.png",
      canonical: ""
    }
  }
);

export default PlasmicAppCards;
/* prettier-ignore-end */
