/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fKsvVS5XnenaZB1533Xwx5
// Component: -F6KTATRxFF2

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import AppLayout from "../../AppLayout"; // plasmic-import: 3-ESBXWrTc3V/component
import { SideEffect } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: fKsvVS5XnenaZB1533Xwx5/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: fKsvVS5XnenaZB1533Xwx5/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fKsvVS5XnenaZB1533Xwx5/projectcss
import sty from "./PlasmicAppCards.module.css"; // plasmic-import: -F6KTATRxFF2/css

import ChipSvgIcon from "./icons/PlasmicIcon__ChipSvg"; // plasmic-import: U8UXyL_So0yp/icon
import VisaIconSvgIcon from "./icons/PlasmicIcon__VisaIconSvg"; // plasmic-import: SxgcbNMZ3u-5/icon
import StarSvgIcon from "./icons/PlasmicIcon__StarSvg"; // plasmic-import: sK8VAJg-RzuJ/icon
import StarLineSvgIcon from "./icons/PlasmicIcon__StarLineSvg"; // plasmic-import: dMJRbC-MfYtA/icon
import TrashSvgIcon from "./icons/PlasmicIcon__TrashSvg"; // plasmic-import: AnEMiUEeSu7J/icon
import PlusSvg2Icon from "./icons/PlasmicIcon__PlusSvg2"; // plasmic-import: IjmbUWMwGAqS/icon
import EnterSvgIcon from "./icons/PlasmicIcon__EnterSvg"; // plasmic-import: x8a8y30xjfZo/icon

createPlasmicElementProxy;

export type PlasmicAppCards__VariantMembers = {};
export type PlasmicAppCards__VariantsArgs = {};
type VariantPropType = keyof PlasmicAppCards__VariantsArgs;
export const PlasmicAppCards__VariantProps = new Array<VariantPropType>();

export type PlasmicAppCards__ArgsType = {};
type ArgPropType = keyof PlasmicAppCards__ArgsType;
export const PlasmicAppCards__ArgProps = new Array<ArgPropType>();

export type PlasmicAppCards__OverridesType = {
  root?: Flex__<"div">;
  appLayout?: Flex__<typeof AppLayout>;
  sideEffect?: Flex__<typeof SideEffect>;
  repeatingCard?: Flex__<"div">;
  hoverCard?: Flex__<"div">;
  hoverCard2?: Flex__<"div">;
};

export interface DefaultAppCardsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAppCards__RenderFunc(props: {
  variants: PlasmicAppCards__VariantsArgs;
  args: PlasmicAppCards__ArgsType;
  overrides: PlasmicAppCards__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "appLayout.popOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "cardIndex",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 100000
      },
      {
        path: "cards",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => []
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicAppCards.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAppCards.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicAppCards.pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={PlasmicAppCards.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicAppCards.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <AppLayout
            data-plasmic-name={"appLayout"}
            data-plasmic-override={overrides.appLayout}
            btnClick={async event => {
              const $steps = {};
            }}
            className={classNames("__wab_instance", sty.appLayout)}
            contents2={
              <React.Fragment>
                <SideEffect
                  data-plasmic-name={"sideEffect"}
                  data-plasmic-override={overrides.sideEffect}
                  className={classNames("__wab_instance", sty.sideEffect)}
                  onMount={async () => {
                    const $steps = {};

                    $steps["runCode"] = true
                      ? (() => {
                          const actionArgs = {
                            customFunction: async () => {
                              return (async () => {
                                async function getLoggedInUser() {
                                  const { data } =
                                    await window.supabase.auth.getSession();
                                  const sessionUser = data?.session?.user;
                                  if (sessionUser) {
                                    return {
                                      id: sessionUser.id,
                                      email: sessionUser.email,
                                      source: "supabase"
                                    };
                                  }
                                  const plasmicUser = window.__PLASMIC_USER__;
                                  if (plasmicUser?.email) {
                                    return {
                                      id: plasmicUser.id,
                                      email: plasmicUser.email,
                                      source: "cookie"
                                    };
                                  }
                                  return null;
                                }
                                return (async () => {
                                  try {
                                    while (!window.__supabaseReady__) {
                                      await new Promise(r =>
                                        setTimeout(r, 100)
                                      );
                                    }
                                    const user = await getLoggedInUser();
                                    if (!user) {
                                      console.warn(
                                        "[Cards] \u274C No logged-in user \u2014 cannot fetch cards."
                                      );
                                      $state.cards = [];
                                      return;
                                    }
                                    console.log(
                                      "[Cards] \uD83D\uDC64 Logged in as:",
                                      user.email,
                                      "(via",
                                      user.source,
                                      ")"
                                    );
                                    const { data, error } =
                                      await window.supabase
                                        .from("user_payment_methods")
                                        .select("*")
                                        .eq("user_id", user.id)
                                        .order("created_at", {
                                          ascending: false
                                        });
                                    if (error) throw error;
                                    console.log(
                                      "[Cards] \uD83D\uDCB3 Loaded cards:",
                                      data
                                    );
                                    $state.cards = data;
                                  } catch (err) {
                                    console.error(
                                      "[Cards] \u274C Failed to fetch cards:",
                                      err
                                    );
                                    $state.cards = [];
                                  }
                                })();
                              })();
                            }
                          };
                          return (({ customFunction }) => {
                            return customFunction();
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runCode"] != null &&
                      typeof $steps["runCode"] === "object" &&
                      typeof $steps["runCode"].then === "function"
                    ) {
                      $steps["runCode"] = await $steps["runCode"];
                    }
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__uVsqc)}>
                  {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                    (() => {
                      try {
                        return $state.cards;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()
                  ).map((__plasmic_item_0, __plasmic_idx_0) => {
                    const currentItem = __plasmic_item_0;
                    const currentIndex = __plasmic_idx_0;
                    return (
                      <div
                        data-plasmic-name={"repeatingCard"}
                        data-plasmic-override={overrides.repeatingCard}
                        className={classNames(
                          projectcss.all,
                          sty.repeatingCard
                        )}
                        key={currentIndex}
                        onMouseEnter={async event => {
                          const $steps = {};

                          $steps["updateCardIndex"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["cardIndex"]
                                  },
                                  operation: 0,
                                  value: currentIndex
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateCardIndex"] != null &&
                            typeof $steps["updateCardIndex"] === "object" &&
                            typeof $steps["updateCardIndex"].then === "function"
                          ) {
                            $steps["updateCardIndex"] =
                              await $steps["updateCardIndex"];
                          }
                        }}
                        onMouseLeave={async event => {
                          const $steps = {};

                          $steps["updateCardIndex"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["cardIndex"]
                                  },
                                  operation: 0,
                                  value: 1000000
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateCardIndex"] != null &&
                            typeof $steps["updateCardIndex"] === "object" &&
                            typeof $steps["updateCardIndex"].then === "function"
                          ) {
                            $steps["updateCardIndex"] =
                              await $steps["updateCardIndex"];
                          }
                        }}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__i8F9F
                          )}
                        >
                          <ChipSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__yZiv3
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__bouaP
                            )}
                          />

                          {(() => {
                            try {
                              return currentItem?.brand == "visa";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return true;
                              }
                              throw e;
                            }
                          })() ? (
                            <VisaIconSvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__pxZdP
                              )}
                              role={"img"}
                            />
                          ) : null}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tyxbt
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__a9H6F
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (
                                    "****  ****  ****  " + currentItem?.last4
                                  );
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "****  ****  ****  ****";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xf3Ru
                          )}
                        >
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___5VvWw
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___97BpH
                                )}
                              >
                                {"Cardholder Name"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__ojG80
                                )}
                              >
                                {""}
                              </div>
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__upccb
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__oew8R
                              )}
                            >
                              {"Expiry Date"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ql65B
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return (
                                      currentItem.exp_month +
                                      " / " +
                                      currentItem.exp_year
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "02/30";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__kzh68
                            )}
                          >
                            {(() => {
                              try {
                                return $state.cardIndex == currentIndex;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return true;
                                }
                                throw e;
                              }
                            })() ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__zJMzJ
                                )}
                              >
                                {"Remove"}
                              </div>
                            ) : null}
                            {(() => {
                              try {
                                return currentItem["default"] == true;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return true;
                                }
                                throw e;
                              }
                            })() ? (
                              <StarSvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__sTQiV
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps["runCode"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          customFunction: async () => {
                                            return (async () => {
                                              return (async () => {
                                                try {
                                                  while (
                                                    !window.__supabaseReady__
                                                  ) {
                                                    await new Promise(r =>
                                                      setTimeout(r, 80)
                                                    );
                                                  }
                                                  const row = currentItem;
                                                  if (!row) {
                                                    console.error(
                                                      "[DefaultCard] No currentItem found."
                                                    );
                                                    return;
                                                  }
                                                  const userId = row.user_id;
                                                  const thisCardId = row.id;
                                                  if (!userId || !thisCardId) {
                                                    console.error(
                                                      "[DefaultCard] Missing user_id or card id."
                                                    );
                                                    return;
                                                  }
                                                  const newValue = !row.default;
                                                  console.log(
                                                    "[DefaultCard] Toggling card",
                                                    thisCardId,
                                                    "\u2192",
                                                    newValue
                                                  );
                                                  const {
                                                    data: updated,
                                                    error: updateError
                                                  } = await window.supabase
                                                    .from(
                                                      "user_payment_methods"
                                                    )
                                                    .update({
                                                      default: newValue
                                                    })
                                                    .eq("id", thisCardId)
                                                    .select()
                                                    .single();
                                                  if (updateError)
                                                    throw updateError;
                                                  console.log(
                                                    "[DefaultCard] Updated this card:",
                                                    updated
                                                  );
                                                  if (newValue) {
                                                    const {
                                                      error: clearError
                                                    } = await window.supabase
                                                      .from(
                                                        "user_payment_methods"
                                                      )
                                                      .update({
                                                        default: false
                                                      })
                                                      .eq("user_id", userId)
                                                      .neq("id", thisCardId);
                                                    if (clearError)
                                                      throw clearError;
                                                    console.log(
                                                      "[DefaultCard] Cleared default from all other cards."
                                                    );
                                                  }
                                                  const {
                                                    data: refreshed,
                                                    error: getError
                                                  } = await window.supabase
                                                    .from(
                                                      "user_payment_methods"
                                                    )
                                                    .select("*")
                                                    .eq("user_id", userId)
                                                    .order("created_at", {
                                                      ascending: false
                                                    });
                                                  if (getError) throw getError;
                                                  console.log(
                                                    "[DefaultCard] Refreshed cards:",
                                                    refreshed
                                                  );
                                                  $state.cards = refreshed;
                                                } catch (err) {
                                                  console.error(
                                                    "[DefaultCard] \u274C Error:",
                                                    err
                                                  );
                                                }
                                              })();
                                            })();
                                          }
                                        };
                                        return (({ customFunction }) => {
                                          return customFunction();
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["runCode"] != null &&
                                    typeof $steps["runCode"] === "object" &&
                                    typeof $steps["runCode"].then === "function"
                                  ) {
                                    $steps["runCode"] = await $steps["runCode"];
                                  }
                                }}
                                role={"img"}
                              />
                            ) : null}
                            {(() => {
                              try {
                                return currentItem["default"] != true;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return true;
                                }
                                throw e;
                              }
                            })() ? (
                              <StarLineSvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___3LtVl
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps["runCode"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          customFunction: async () => {
                                            return (async () => {
                                              return (async () => {
                                                try {
                                                  while (
                                                    !window.__supabaseReady__
                                                  ) {
                                                    await new Promise(r =>
                                                      setTimeout(r, 80)
                                                    );
                                                  }
                                                  const row = currentItem;
                                                  if (!row) {
                                                    console.error(
                                                      "[DefaultCard] No currentItem found."
                                                    );
                                                    return;
                                                  }
                                                  const userId = row.user_id;
                                                  const thisCardId = row.id;
                                                  if (!userId || !thisCardId) {
                                                    console.error(
                                                      "[DefaultCard] Missing user_id or card id."
                                                    );
                                                    return;
                                                  }
                                                  const newValue = !row.default;
                                                  console.log(
                                                    "[DefaultCard] Toggling card",
                                                    thisCardId,
                                                    "\u2192",
                                                    newValue
                                                  );
                                                  const {
                                                    data: updated,
                                                    error: updateError
                                                  } = await window.supabase
                                                    .from(
                                                      "user_payment_methods"
                                                    )
                                                    .update({
                                                      default: newValue
                                                    })
                                                    .eq("id", thisCardId)
                                                    .select()
                                                    .single();
                                                  if (updateError)
                                                    throw updateError;
                                                  console.log(
                                                    "[DefaultCard] Updated this card:",
                                                    updated
                                                  );
                                                  if (newValue) {
                                                    const {
                                                      error: clearError
                                                    } = await window.supabase
                                                      .from(
                                                        "user_payment_methods"
                                                      )
                                                      .update({
                                                        default: false
                                                      })
                                                      .eq("user_id", userId)
                                                      .neq("id", thisCardId);
                                                    if (clearError)
                                                      throw clearError;
                                                    console.log(
                                                      "[DefaultCard] Cleared default from all other cards."
                                                    );
                                                  }
                                                  const {
                                                    data: refreshed,
                                                    error: getError
                                                  } = await window.supabase
                                                    .from(
                                                      "user_payment_methods"
                                                    )
                                                    .select("*")
                                                    .eq("user_id", userId)
                                                    .order("created_at", {
                                                      ascending: false
                                                    });
                                                  if (getError) throw getError;
                                                  console.log(
                                                    "[DefaultCard] Refreshed cards:",
                                                    refreshed
                                                  );
                                                  $state.cards = refreshed;
                                                } catch (err) {
                                                  console.error(
                                                    "[DefaultCard] \u274C Error:",
                                                    err
                                                  );
                                                }
                                              })();
                                            })();
                                          }
                                        };
                                        return (({ customFunction }) => {
                                          return customFunction();
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["runCode"] != null &&
                                    typeof $steps["runCode"] === "object" &&
                                    typeof $steps["runCode"].then === "function"
                                  ) {
                                    $steps["runCode"] = await $steps["runCode"];
                                  }
                                }}
                                role={"img"}
                              />
                            ) : null}
                          </div>
                        </div>
                        {false ? (
                          <div
                            data-plasmic-name={"hoverCard"}
                            data-plasmic-override={overrides.hoverCard}
                            className={classNames(
                              projectcss.all,
                              sty.hoverCard
                            )}
                          >
                            <TrashSvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg___1OrnV
                              )}
                              role={"img"}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__tmCi4
                              )}
                            >
                              {"Remove Card"}
                            </div>
                          </div>
                        ) : null}
                      </div>
                    );
                  })}
                  <div
                    data-plasmic-name={"hoverCard2"}
                    data-plasmic-override={overrides.hoverCard2}
                    className={classNames(projectcss.all, sty.hoverCard2)}
                  >
                    <PlusSvg2Icon
                      className={classNames(projectcss.all, sty.svg___7EnXr)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__z1LDk
                      )}
                    >
                      {"Add Card"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fVyrE)}
                    >
                      {false ? (
                        <EnterSvgIcon
                          className={classNames(projectcss.all, sty.svg__ySqyM)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r3JXy,
                          "geologica-h1"
                        )}
                      >
                        {"C"}
                      </div>
                    </div>
                  </div>
                </div>
                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qlkZg)}
                    onClick={async event => {
                      const $steps = {};

                      $steps["runCode"] = true
                        ? (() => {
                            const actionArgs = {
                              customFunction: async () => {
                                return (async () => {
                                  async function addCard() {
                                    console.log("\u25B6️ addCard() clicked");
                                    const authKey = Object.keys(
                                      localStorage
                                    ).find(
                                      k =>
                                        k.startsWith("sb-") &&
                                        k.endsWith("-auth-token")
                                    );
                                    if (!authKey) {
                                      console.error(
                                        "\u274C No Supabase auth token key found in localStorage"
                                      );
                                      return;
                                    }
                                    const raw = localStorage.getItem(authKey);
                                    if (!raw) {
                                      console.error(
                                        "\u274C Supabase auth token missing"
                                      );
                                      return;
                                    }
                                    let session;
                                    try {
                                      session = JSON.parse(raw);
                                    } catch (err) {
                                      console.error(
                                        "\u274C Failed to parse Supabase auth JSON:",
                                        err
                                      );
                                      return;
                                    }
                                    const accessToken = session?.access_token;
                                    if (!accessToken) {
                                      console.error(
                                        "\u274C No access_token found in session"
                                      );
                                      return;
                                    }
                                    console.log(
                                      "\uD83D\uDD11 Supabase access token found"
                                    );
                                    let res;
                                    try {
                                      res = await fetch(
                                        "/api/stripe/add-card",
                                        {
                                          method: "POST",
                                          headers: {
                                            Authorization: `Bearer ${accessToken}`
                                          }
                                        }
                                      );
                                    } catch (err) {
                                      console.error(
                                        "\u274C Network error calling /api/stripe/add-card:",
                                        err
                                      );
                                      return;
                                    }
                                    console.log(
                                      "\uD83D\uDCE1 Response status:",
                                      res.status
                                    );
                                    let data;
                                    try {
                                      data = await res.json();
                                    } catch (err) {
                                      console.error(
                                        "\u274C Failed to parse JSON response:",
                                        err
                                      );
                                      return;
                                    }
                                    if (data.error) {
                                      console.error(
                                        "\u274C API Error:",
                                        data.error,
                                        data.detail
                                      );
                                      return;
                                    }
                                    if (data.url) {
                                      console.log(
                                        "\u27A1️ Redirecting to:",
                                        data.url
                                      );
                                      window.location.href = data.url;
                                      return;
                                    }
                                    console.warn(
                                      "\u26A0️ /api/stripe/add-card returned no URL"
                                    );
                                  }
                                  return addCard();
                                })();
                              }
                            };
                            return (({ customFunction }) => {
                              return customFunction();
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["runCode"] != null &&
                        typeof $steps["runCode"] === "object" &&
                        typeof $steps["runCode"].then === "function"
                      ) {
                        $steps["runCode"] = await $steps["runCode"];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__t4QXm
                      )}
                    >
                      {"Add Card"}
                    </div>
                  </div>
                ) : null}
              </React.Fragment>
            }
            navBtnclick={async event => {
              const $steps = {};

              $steps["runCode"] = true
                ? (() => {
                    const actionArgs = {
                      customFunction: async () => {
                        return (async () => {
                          async function addCard() {
                            console.log("\u25B6️ addCard() clicked");
                            const authKey = Object.keys(localStorage).find(
                              k =>
                                k.startsWith("sb-") && k.endsWith("-auth-token")
                            );
                            if (!authKey) {
                              console.error(
                                "\u274C No Supabase auth token key found in localStorage"
                              );
                              return;
                            }
                            const raw = localStorage.getItem(authKey);
                            if (!raw) {
                              console.error(
                                "\u274C Supabase auth token missing"
                              );
                              return;
                            }
                            let session;
                            try {
                              session = JSON.parse(raw);
                            } catch (err) {
                              console.error(
                                "\u274C Failed to parse Supabase auth JSON:",
                                err
                              );
                              return;
                            }
                            const accessToken = session?.access_token;
                            if (!accessToken) {
                              console.error(
                                "\u274C No access_token found in session"
                              );
                              return;
                            }
                            console.log(
                              "\uD83D\uDD11 Supabase access token found"
                            );
                            let res;
                            try {
                              res = await fetch("/api/stripe/add-card", {
                                method: "POST",
                                headers: {
                                  Authorization: `Bearer ${accessToken}`
                                }
                              });
                            } catch (err) {
                              console.error(
                                "\u274C Network error calling /api/stripe/add-card:",
                                err
                              );
                              return;
                            }
                            console.log(
                              "\uD83D\uDCE1 Response status:",
                              res.status
                            );
                            let data;
                            try {
                              data = await res.json();
                            } catch (err) {
                              console.error(
                                "\u274C Failed to parse JSON response:",
                                err
                              );
                              return;
                            }
                            if (data.error) {
                              console.error(
                                "\u274C API Error:",
                                data.error,
                                data.detail
                              );
                              return;
                            }
                            if (data.url) {
                              console.log("\u27A1️ Redirecting to:", data.url);
                              window.location.href = data.url;
                              return;
                            }
                            console.warn(
                              "\u26A0️ /api/stripe/add-card returned no URL"
                            );
                          }
                          return addCard();
                        })();
                      }
                    };
                    return (({ customFunction }) => {
                      return customFunction();
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["runCode"] != null &&
                typeof $steps["runCode"] === "object" &&
                typeof $steps["runCode"].then === "function"
              ) {
                $steps["runCode"] = await $steps["runCode"];
              }
            }}
            onPopOpenChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["appLayout", "popOpen"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            page={"cards"}
            popOpen={generateStateValueProp($state, ["appLayout", "popOpen"])}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "appLayout",
    "sideEffect",
    "repeatingCard",
    "hoverCard",
    "hoverCard2"
  ],
  appLayout: [
    "appLayout",
    "sideEffect",
    "repeatingCard",
    "hoverCard",
    "hoverCard2"
  ],
  sideEffect: ["sideEffect"],
  repeatingCard: ["repeatingCard", "hoverCard"],
  hoverCard: ["hoverCard"],
  hoverCard2: ["hoverCard2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  appLayout: typeof AppLayout;
  sideEffect: typeof SideEffect;
  repeatingCard: "div";
  hoverCard: "div";
  hoverCard2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAppCards__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAppCards__VariantsArgs;
    args?: PlasmicAppCards__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAppCards__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAppCards__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAppCards__ArgProps,
          internalVariantPropNames: PlasmicAppCards__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAppCards__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAppCards";
  } else {
    func.displayName = `PlasmicAppCards.${nodeName}`;
  }
  return func;
}

export const PlasmicAppCards = Object.assign(
  // Top-level PlasmicAppCards renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    appLayout: makeNodeComponent("appLayout"),
    sideEffect: makeNodeComponent("sideEffect"),
    repeatingCard: makeNodeComponent("repeatingCard"),
    hoverCard: makeNodeComponent("hoverCard"),
    hoverCard2: makeNodeComponent("hoverCard2"),

    // Metadata about props expected for PlasmicAppCards
    internalVariantProps: PlasmicAppCards__VariantProps,
    internalArgProps: PlasmicAppCards__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Cards | AdBuy",
      description: "",
      ogImageSrc:
        "https://site-assets.plasmic.app/d1eac95f3934b1653900f60b4f2a55c6.png",
      canonical: ""
    }
  }
);

export default PlasmicAppCards;
/* prettier-ignore-end */
